CREATE TABLE [ims].[FactTransact] (
    [TransactKey]            BIGINT          NULL,
    [Identifier]             VARCHAR (8000)  NULL,
    [ReportedDate]           DATETIME2 (6)   NULL,
    [TradeDate]              DATETIME2 (6)   NULL,
    [SettlementDate]         DATETIME2 (6)   NULL,
    [CanceledDate]           DATETIME2 (6)   NULL,
    [TradeType]              VARCHAR (8000)  NULL,
    [BuyProtection]          VARCHAR (8000)  NULL,
    [Quantity]               DECIMAL (18, 4) NULL,
    [PriceLocal]             DECIMAL (18, 4) NULL,
    [PriceBase]              DECIMAL (18, 4) NULL,
    [PriceUSD]               DECIMAL (18, 4) NULL,
    [CommissionLocal]        DECIMAL (18, 4) NULL,
    [CommissionBase]         DECIMAL (18, 4) NULL,
    [CommissionUSD]          DECIMAL (18, 4) NULL,
    [ImpliedCommissionLocal] DECIMAL (18, 4) NULL,
    [ImpliedCommissionBase]  DECIMAL (18, 4) NULL,
    [ImpliedCommissionUSD]   DECIMAL (18, 4) NULL,
    [FeesLocal]              DECIMAL (18, 4) NULL,
    [FeesBase]               DECIMAL (18, 4) NULL,
    [FeesUSD]                DECIMAL (18, 4) NULL,
    [NetAmountLocal]         DECIMAL (18, 4) NULL,
    [NetAmountBase]          DECIMAL (18, 4) NULL,
    [NetAmountUSD]           DECIMAL (18, 4) NULL,
    [GrossAmountLocal]       DECIMAL (18, 4) NULL,
    [GrossAmountBase]        DECIMAL (18, 4) NULL,
    [GrossAmountUSD]         DECIMAL (18, 4) NULL,
    [CostLocal]              DECIMAL (18, 4) NULL,
    [CostBase]               DECIMAL (18, 4) NULL,
    [CostUSD]                DECIMAL (18, 4) NULL,
    [GainLossLocal]          DECIMAL (18, 4) NULL,
    [PercentGainLossLocal]   DECIMAL (18, 4) NULL,
    [PercentGainLossBase]    DECIMAL (18, 4) NULL,
    [PercentGainLossUSD]     DECIMAL (18, 4) NULL,
    [AccruedInterestLocal]   DECIMAL (18, 4) NULL,
    [AccruedInterestBase]    DECIMAL (18, 4) NULL,
    [AccruedInterestUSD]     DECIMAL (18, 4) NULL,
    [DateKey]                BIGINT          NULL,
    [SecurityKey]            BIGINT          NULL,
    [PortfolioKey]           BIGINT          NULL,
    [BrokerKey]              BIGINT          NULL,
    [CreatedBy]              VARCHAR (8000)  NULL,
    [CreatedDate]            DATETIME2 (6)   NULL,
    [UpdatedBy]              VARCHAR (8000)  NULL,
    [UpdatedDate]            DATETIME2 (6)   NULL
);


GO