CREATE TABLE [ims].[FactRptPosAnalytics] (
    [PosAnalyticsKey]     INT             NULL,
    [SecurityKey]         BIGINT          NULL,
    [LinkAssetClassKey]   BIGINT          NULL,
    [LinkSecurityTypeKey] BIGINT          NULL,
    [CurrencyKey]         BIGINT          NULL,
    [CountryKey]          BIGINT          NULL,
    [ShortName]           VARCHAR (8000)  NULL,
    [LongName]            VARCHAR (8000)  NULL,
    [SecurityDescription] VARCHAR (8000)  NULL,
    [SourceSystemKey]     BIGINT          NULL,
    [IndustryGICS]        VARCHAR (8000)  NULL,
    [SubindustryGICS]     VARCHAR (8000)  NULL,
    [SectorGICS]          VARCHAR (8000)  NULL,
    [IndustryGroupGICS]   VARCHAR (8000)  NULL,
    [SubSectorGICS]       VARCHAR (8000)  NULL,
    [EffectiveDt]         DATETIME2 (6)   NULL,
    [FormatedEffectiveDt] DATE            NULL,
    [NextDividendPaydate] DATE            NULL,
    [LastDividendPaydate] DATE            NULL,
    [FIGI]                VARCHAR (8000)  NULL,
    [SYMBOL]              VARCHAR (8000)  NULL,
    [CUSIP]               VARCHAR (8000)  NULL,
    [ISIN]                VARCHAR (8000)  NULL,
    [SEDOL]               VARCHAR (8000)  NULL,
    [Identifier]          VARCHAR (8000)  NULL,
    [PFBMCode]            VARCHAR (8000)  NULL,
    [AsOfDate]            DATETIME2 (6)   NULL,
    [IsPortfolio]         BIT             NULL,
    [UnPivotValue]        DECIMAL (18, 4) NULL,
    [Metric]              VARCHAR (8000)  NULL,
    [CreatedBy]           VARCHAR (8000)  NULL,
    [CreatedDate]         DATETIME2 (6)   NULL,
    [UpdatedBy]           VARCHAR (8000)  NULL,
    [UpdatedDate]         DATETIME2 (6)   NULL
);


GO