CREATE TABLE [ims].[RptSecurityAnalytics] (
    [SecurityAnalyticsKey] BIGINT          NULL,
    [SecurityKey]          BIGINT          NULL,
    [LinkAssetClassKey]    BIGINT          NULL,
    [LinkSecurityTypeKey]  BIGINT          NULL,
    [CurrencyKey]          BIGINT          NULL,
    [CountryKey]           BIGINT          NULL,
    [ShortName]            VARCHAR (8000)  NULL,
    [LongName]             VARCHAR (8000)  NULL,
    [SecurityDescription]  VARCHAR (8000)  NULL,
    [SourceSystemKey]      BIGINT          NULL,
    [IndustryGICS]         VARCHAR (8000)  NULL,
    [SubindustryGICS]      VARCHAR (8000)  NULL,
    [SectorGICS]           VARCHAR (8000)  NULL,
    [IndustryGroupGICS]    VARCHAR (8000)  NULL,
    [SubSectorGICS]        VARCHAR (8000)  NULL,
    [ProductType]          VARCHAR (8000)  NULL,
    [Coupon]               DECIMAL (18, 4) NULL,
    [EffectiveDt]          DATE            NULL,
    [PriceStartDay]        DECIMAL (18, 4) NULL,
    [PriceLastEOD]         DECIMAL (18, 4) NULL,
    [DividendYield]        DECIMAL (18, 4) NULL,
    [DividendAmount]       DECIMAL (18, 4) NULL,
    [NextDividendPaydate]  DATE            NULL,
    [LastDividendPaydate]  DATE            NULL,
    [FiftyTwoWeekHigh]     DECIMAL (18, 4) NULL,
    [FiftyTwoWeekLow]      DECIMAL (18, 4) NULL,
    [CurrentYearHigh]      DECIMAL (18, 4) NULL,
    [CurrentYearLow]       DECIMAL (18, 4) NULL,
    [MarketPrice]          DECIMAL (18, 4) NULL,
    [Factor]               DECIMAL (18, 4) NULL,
    [OneMCPR]              DECIMAL (18, 4) NULL,
    [ThreeMCPR]            DECIMAL (18, 4) NULL,
    [SixMCPR]              DECIMAL (18, 4) NULL,
    [TwelveMCPR]           DECIMAL (18, 4) NULL,
    [DTC]                  DECIMAL (18, 4) NULL,
    [KeyRateDur6M]         DECIMAL (18, 4) NULL,
    [KeyRateDur1Yr]        DECIMAL (18, 4) NULL,
    [KeyRateDur2y]         DECIMAL (18, 4) NULL,
    [KeyRateDur3y]         DECIMAL (18, 4) NULL,
    [KeyRateDur5y]         DECIMAL (18, 4) NULL,
    [KeyRateDur7y]         DECIMAL (18, 4) NULL,
    [KeyRateDur10y]        DECIMAL (18, 4) NULL,
    [WAC]                  DECIMAL (18, 4) NULL,
    [WAM]                  DECIMAL (18, 4) NULL,
    [ModifiedDur]          DECIMAL (18, 4) NULL,
    [SpreadDur]            DECIMAL (18, 4) NULL,
    [OAS]                  DECIMAL (18, 4) NULL,
    [Convexity]            DECIMAL (18, 4) NULL,
    [AdjustedDur]          DECIMAL (18, 4) NULL,
    [YTM]                  DECIMAL (18, 4) NULL,
    [FIGI]                 VARCHAR (8000)  NULL,
    [SYMBOL]               VARCHAR (8000)  NULL,
    [CUSIP]                VARCHAR (8000)  NULL,
    [ISIN]                 VARCHAR (8000)  NULL,
    [SEDOL]                VARCHAR (8000)  NULL,
    [PE]                   DECIMAL (18, 4) NULL,
    [Beta]                 DECIMAL (18, 4) NULL,
    [Identifier]           VARCHAR (8000)  NULL,
    [Delta]                DECIMAL (19, 4) NULL,
    [ENV]                  DECIMAL (18, 4) NULL,
    [SOC]                  DECIMAL (18, 4) NULL,
    [GOV]                  DECIMAL (18, 4) NULL,
    [ESG]                  DECIMAL (18, 4) NULL,
    [CreatedBy]            VARCHAR (8000)  NULL,
    [CreatedDate]          DATETIME2 (6)   NULL,
    [UpdatedBy]            VARCHAR (8000)  NULL,
    [UpdatedDate]          DATETIME2 (6)   NULL
);


GO